services:
  telegram-to-rss:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      tags:
        - "telegram-to-rss:dev"
    container_name: telegram-to-rss
    restart: always
    env_file: ../.env
    ports:
      - 3042:3042
    volumes:
      - data:/data
    depends_on:
      - torproxy

  torproxy:
    image: dperson/torproxy:latest
    container_name: tgtorss-torproxy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data: null

networks: {}