 services:
  telegram-to-rss:
    image: aigoncharov/telegram-to-rss:latest
    container_name: telegram-to-rss
    restart: always
    environment:
      - TG_API_ID=REPLACE_ME
      - TG_API_HASH=REPLACE_ME
      - TG_PASSWORD=REPLACE_ME
      - BASE_URL=REPLACE_ME
      - PROXY_URL=socks5://torproxy:9050
    ports:
      - 3042:3042
    volumes:
      - data:/data
    depends_on:
      - torproxy

  torproxy:
    image: dperson/torproxy:latest
    container_name: torproxy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data: null

networks: {}